# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: petclinic
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YTExNDAzZjk5MWIxYmU1MzM4MTFmYzUxNjUyZDNiYjQ0ZDA2MzQ0ODljMDJkNzdhMjcxZGE2NzgyMjU1NGRhOGVlOTY0Yzg1NDY2OTc5MDlhYzU0M2E2YTJmZDlhYmM3YWRkMjZlNWJlNDU5MWY5NDUyMzc0MTZjYWFlMjgzODc=
