package com.stg.petclinic.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnimalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnimalAllPropertiesEquals(Animal expected, Animal actual) {
        assertAnimalAutoGeneratedPropertiesEquals(expected, actual);
        assertAnimalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnimalAllUpdatablePropertiesEquals(Animal expected, Animal actual) {
        assertAnimalUpdatableFieldsEquals(expected, actual);
        assertAnimalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnimalAutoGeneratedPropertiesEquals(Animal expected, Animal actual) {
        assertThat(actual)
            .as("Verify Animal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnimalUpdatableFieldsEquals(Animal expected, Animal actual) {
        assertThat(actual)
            .as("Verify Animal relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getEspece()).as("check espece").isEqualTo(expected.getEspece()))
            .satisfies(a -> assertThat(a.getDateNaissance()).as("check dateNaissance").isEqualTo(expected.getDateNaissance()))
            .satisfies(a -> assertThat(a.getSexe()).as("check sexe").isEqualTo(expected.getSexe()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnimalUpdatableRelationshipsEquals(Animal expected, Animal actual) {
        assertThat(actual)
            .as("Verify Animal relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
