package com.stg.petclinic.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedecinAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedecinAllPropertiesEquals(Medecin expected, Medecin actual) {
        assertMedecinAutoGeneratedPropertiesEquals(expected, actual);
        assertMedecinAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedecinAllUpdatablePropertiesEquals(Medecin expected, Medecin actual) {
        assertMedecinUpdatableFieldsEquals(expected, actual);
        assertMedecinUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedecinAutoGeneratedPropertiesEquals(Medecin expected, Medecin actual) {
        assertThat(actual)
            .as("Verify Medecin auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedecinUpdatableFieldsEquals(Medecin expected, Medecin actual) {
        assertThat(actual)
            .as("Verify Medecin relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPrenom()).as("check prenom").isEqualTo(expected.getPrenom()))
            .satisfies(a -> assertThat(a.getSpecialite()).as("check specialite").isEqualTo(expected.getSpecialite()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedecinUpdatableRelationshipsEquals(Medecin expected, Medecin actual) {
        assertThat(actual)
            .as("Verify Medecin relationships")
            .satisfies(a -> assertThat(a.getClinique()).as("check clinique").isEqualTo(expected.getClinique()));
    }
}
