package com.stg.petclinic.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PeserAnimalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeserAnimalAllPropertiesEquals(PeserAnimal expected, PeserAnimal actual) {
        assertPeserAnimalAutoGeneratedPropertiesEquals(expected, actual);
        assertPeserAnimalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeserAnimalAllUpdatablePropertiesEquals(PeserAnimal expected, PeserAnimal actual) {
        assertPeserAnimalUpdatableFieldsEquals(expected, actual);
        assertPeserAnimalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeserAnimalAutoGeneratedPropertiesEquals(PeserAnimal expected, PeserAnimal actual) {
        assertThat(actual)
            .as("Verify PeserAnimal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeserAnimalUpdatableFieldsEquals(PeserAnimal expected, PeserAnimal actual) {
        assertThat(actual)
            .as("Verify PeserAnimal relevant properties")
            .satisfies(a -> assertThat(a.getPoids()).as("check poids").isEqualTo(expected.getPoids()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeserAnimalUpdatableRelationshipsEquals(PeserAnimal expected, PeserAnimal actual) {
        assertThat(actual)
            .as("Verify PeserAnimal relationships")
            .satisfies(a -> assertThat(a.getRendezVous()).as("check rendezVous").isEqualTo(expected.getRendezVous()))
            .satisfies(a -> assertThat(a.getAnimal()).as("check animal").isEqualTo(expected.getAnimal()));
    }
}
