package com.stg.petclinic.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RendezVousAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRendezVousAllPropertiesEquals(RendezVous expected, RendezVous actual) {
        assertRendezVousAutoGeneratedPropertiesEquals(expected, actual);
        assertRendezVousAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRendezVousAllUpdatablePropertiesEquals(RendezVous expected, RendezVous actual) {
        assertRendezVousUpdatableFieldsEquals(expected, actual);
        assertRendezVousUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRendezVousAutoGeneratedPropertiesEquals(RendezVous expected, RendezVous actual) {
        assertThat(actual)
            .as("Verify RendezVous auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRendezVousUpdatableFieldsEquals(RendezVous expected, RendezVous actual) {
        assertThat(actual)
            .as("Verify RendezVous relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getDuree()).as("check duree").isEqualTo(expected.getDuree()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRendezVousUpdatableRelationshipsEquals(RendezVous expected, RendezVous actual) {
        assertThat(actual)
            .as("Verify RendezVous relationships")
            .satisfies(a -> assertThat(a.getAnimal()).as("check animal").isEqualTo(expected.getAnimal()))
            .satisfies(a -> assertThat(a.getClinique()).as("check clinique").isEqualTo(expected.getClinique()))
            .satisfies(a -> assertThat(a.getMedecin()).as("check medecin").isEqualTo(expected.getMedecin()));
    }
}
